#!/usr/bin/env bash
set -euo pipefail
trap 'echo "ERROR: build failed in ${BASH_SOURCE[0]} at line ${LINENO}" >&2' ERR

cd $SCRIPT_DIR
echo "HELLO FROM build libs: $SCRIPT_DIR"

if [ ! -d "$SOURCE" ]; then
  mkdir -p "$SOURCE"
fi

echo "Starting LIB_X264 build" >&2
if [ ! -f "$BUILD/lib/libx264.so" ]; then
  $SCRIPT_DIR/build_h264
else
  echo "Found existing x264" >&2
fi

echo "Starting LIB_X265 build" >&2
if [ ! -f "$BUILD/lib/libx265.so" ]; then
$SCRIPT_DIR/build_h265
else
echo "Found existing x265" >&2
fi

echo "Starting FDK_AAC build" >&2
if [ ! -f "$BUILD/lib/libfdk-aac.so" ]; then
  $SCRIPT_DIR/build_aac
else
  echo "Found existing AAC" >&2
fi

echo "Starting LIB_SDL2 build" >&2
if [ ! -f "$BUILD/lib/libSDL2.so" ]; then
  $SCRIPT_DIR/build_sdl2
else
  echo "Found existing SDL2" >&2
fi

echo "Starting FFMPEG build" >&2
if [ ! -f "$BUILD/lib/libavcodec.so" ]; then
  $SCRIPT_DIR/build_ffmpeg
else
  echo "Found existing FFMPEG" >&2
fi


