#!/usr/bin/env bash
set -euo pipefail

cd "$SOURCE"
if [ ! -d "SDL-release-2.32.6" ]; then
    wget -O release-2.32.6.tar.gz https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.6.tar.gz
    tar xzvf release-2.32.6.tar.gz
fi
cd SDL-release-2.32.6
./configure --prefix="$BUILD"
make -j"$(nproc)"
make install
