#!/usr/bin/env bash

cd $SOURCE

# ALTERNATE SOURCES FOR CODE
#if [ ! -d "x265_4.1" ]; then
#    wget -O x265.tar.bz2 https://bitbucket.org/multicoreware/x265_git/get/master.tar.bz2
#    tar xjvf x265.tar.bz2
#    wget http://ftp.videolan.org/pub/videolan/x265/x265_4.1.tar.gz
#    tar xzvf x265_4.1.tar.gz
#fi

git clone https://bitbucket.org/multicoreware/x265_git
cd x265_git/build/linux
cmake ../../source -DCMAKE_INSTALL_PREFIX="$BUILD"
make 
make install