#!/usr/bin/env bash

cd $SOURCE

# ALTERNATE SOURCES FOR CODE
#if [ ! -d "x265_4.1" ]; then
#    wget -O x265.tar.bz2 https://bitbucket.org/multicoreware/x265_git/get/master.tar.bz2
#    tar xjvf x265.tar.bz2
#    wget http://ftp.videolan.org/pub/videolan/x265/x265_4.1.tar.gz
#    tar xzvf x265_4.1.tar.gz
#fi

git -C x265_git pull 2> /dev/null || git clone --depth 1 https://bitbucket.org/multicoreware/x265_git
#git clone https://bitbucket.org/multicoreware/x265_git
cd x265_git/build/linux

PATH="$BIN:$PATH" cmake -G "Unix Makefiles" -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_SHARED=on ../../source && \
PATH="$BIN:$PATH" make  -j$(nproc) && \
make install