#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <project directory>" >&2
  exit 1
fi
if [ ! -d "$1" ]; then
  echo "Project directory $1 does not exist, please enter a valid directory" >&2
  exit 1
fi
if [[ ! -f "$1/pyproject.toml" && ! -f "$1/setup.py" ]]; then
  echo "Invalid Python project directory, did not find either pyproject.toml or setup.py in $1" >&2
  exit 1
fi

PROJECT_DIR="$(cd "$1" && pwd)"
echo "Project Directory: $PROJECT_DIR" >&2

case "$(uname -m)" in
  x86_64|amd64|i386|i686) ARCH="x86_64" ;;
  aarch64|arm64|arm*)     ARCH="aarch64" ;;
  *)                      ARCH="UNKNOWN" ;;
esac
export ARCH

BASE="$PWD"
export LD_RUN_PATH='$ORIGIN'

dnf install -y wget nasm
export SOURCE="$BASE/source"
export BUILD="$BASE/build"
export BIN="$BASE/usr/local/bin"
export ACLOCAL_PATH=/usr/share/aclocal
export PKG_CONFIG_PATH="$BUILD/lib/pkgconfig"
export SDL2_DIR="$BUILD"
export DIR_NAME="$(cd "$(dirname "$0")" && pwd)"
"$DIR_NAME/build_libs"

venvs=("py314")
#venvs=("py310" "py311" "py312" "py313" "py314")
for venv in "${venvs[@]}"; do
  echo "Python venv: $venv" >&2
  if [ ! -d "$BASE/$venv" ]; then
    version="${venv:2}"
    version="${version:0:1}.${version:1}"
    echo "version $version"
    python${version} -m venv $BASE/$venv
    . $BASE/$venv/bin/activate
    pip install --upgrade pip
    deactivate
  fi
  source "$BASE/$venv/bin/activate"
  python --version

  pip install build auditwheel patchelf
  cd $PROJECT_DIR
  python -m build

  if [[ "$ARCH" == "x86_64" ]]; then
    echo "processor architecture is x86"
    auditwheel repair dist/*.whl --plat manylinux_2_28_x86_64
  elif [[ "$ARCH" == "aarch64" ]]; then
    echo "aarch64"
    auditwheel repair dist/*.whl --plat manylinux_2_28_aarch64
  else
    echo "ERROR: UNABLE TO BUILD WHEEL - Unknown architecture"
  fi

  deactivate
done
