#!/usr/bin/bash

virt-install --name=libavio-vm \
--vcpus=4 \
--memory=8192 \
--cdrom=vm/iso/linuxmint-21-cinnamon-64bit.iso \
--disk path=vm/hda/libavio.qcow2,size=64,format=qcow2 \
--os-variant=linux2020
