#!/usr/bin/env bash

cd $SOURCE

# ALTERNATE SOURCES FOR CODE
#if [ ! -d "x265_4.1" ]; then
#    wget -O x265.tar.bz2 https://bitbucket.org/multicoreware/x265_git/get/master.tar.bz2
#    tar xjvf x265.tar.bz2
#    wget http://ftp.videolan.org/pub/videolan/x265/x265_4.1.tar.gz
#    tar xzvf x265_4.1.tar.gz
#fi

git clone https://bitbucket.org/multicoreware/x265_git
cd x265_git/build/linux
cmake ../../source -DCMAKE_INSTALL_PREFIX="$BUILD"
make 
make install

# for some reason, they tweak the lib during build, this turns it back
cd $BUILD/lib
for entry in $(otool -l libx265.dylib | grep -A5 LC_ID_DYLIB | grep name | awk '{print $2}'); do
    echo "entry: $entry"
    file=$(basename $entry)
    install_name_tool -id $BUILD/lib/$file $file
done
