#!/usr/bin/env bash
set -euo pipefail
trap 'echo "ERROR: build failed in ${BASH_SOURCE[0]} at line ${LINENO}" >&2' ERR

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <project directory>" >&2
  exit 1
fi
if [ ! -d "$1" ]; then
  echo "Project directory $1 does not exist, please enter a valid directory" >&2
  exit 1
fi
if [[ ! -f "$1/pyproject.toml" && ! -f "$1/setup.py" ]]; then
  echo "Invalid Python project directory, did not find either pyproject.toml or setup.py in $1" >&2
  exit 1
fi

PROJECT_DIR="$(cd "$1" && pwd)"
echo "Project Directory: $PROJECT_DIR" >&2

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo >> $HOME/.zprofile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"
brew install wget automake nasm libtool pkgconfig

mkdir -p $HOME/ffmpeg_sources 
mkdir -p $HOME/bin
mkdir -p $HOME/sources
mkdir -p $HOME/libxml2_sources

export BUILD="$HOME/ffmpeg_build"
export SOURCE="$HOME/ffmpeg_sources"
export BIN="$HOME/bin"
export MACOSX_DEPLOYMENT_TARGET=15.0
export PKG_CONFIG_PATH=$HOME/ffmpeg_build/lib/pkgconfig
export SDL2_DIR=$HOME/ffmpeg_build
export LIBXML2_INCLUDE_DIRS=$HOME/libxml2_build/include/libxml2
export LIBXML2_LIBRARIES=$HOME/libxml2_build/lib/libxml2.dylib

export PATH=/usr/local/bin:$PATH

rm -rf "$BUILD"

"$PROJECT_DIR/scripts/mac/build_cmake_mac"
"$PROJECT_DIR/scripts/mac/build_h264"
"$PROJECT_DIR/scripts/mac/build_h265"
#"$PROJECT_DIR/scripts/mac/fix_x265_rpath"
"$PROJECT_DIR/scripts/mac/build_aac"
"$PROJECT_DIR/scripts/mac/build_sdl2"
"$PROJECT_DIR/scripts/mac/build_ffmpeg" 

versions=("3.10.11" "3.11.9" "3.12.9" "3.13.2" "3.14.2")
for version in "${versions[@]}"; do
    "$PROJECT_DIR/scripts/mac/install_python" $version
done

cd $PROJECT_DIR
first_pass=1
#venvs=("py310" "py311" "py312" "py313" "py314")
venvs=("py313")
for venv in "${venvs[@]}"; do
    source $HOME/$venv/bin/activate
    python --version
    pip install build
    if [ $first_pass == 1 ]; then
        pip install .
        pyname=$(ls $HOME/$venv/lib | awk '{print $1}')
        pydir=$HOME/$venv/lib/$pyname/site-packages
        modname=$(ls $pydir/avio/avio*.so | awk '{print $1}')
        export executable=$modname
        export sourcedir=$PROJECT_DIR/avio
        $PROJECT_DIR/scripts/mac/copy_libs
        $PROJECT_DIR/scripts/mac/install_name
    fi
    first_pass=0
    python -m build .
    deactivate
done
