#!/usr/bin/env bash
set -euo pipefail
trap 'echo "ERROR: build failed in ${BASH_SOURCE[0]} at line ${LINENO}" >&2' ERR

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <project directory>" >&2
  exit 1
fi
if [ ! -d "$1" ]; then
  echo "Project directory $1 does not exist, please enter a valid directory" >&2
  exit 1
fi
if [[ ! -f "$1/pyproject.toml" && ! -f "$1/setup.py" ]]; then
  echo "Invalid Python project directory, did not find either pyproject.toml or setup.py in $1" >&2
  exit 1
fi

BASE="$PWD"
PROJECT_DIR="$(cd "$1" && pwd)"
echo "Project Directory: $PROJECT_DIR" >&2

if [ ! -f /opt/homebrew/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo >> $HOME/.zprofile
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
    brew install wget automake nasm libtool pkgconfig cmake ninja
fi

export BUILD="$BASE/build"
export SOURCE="$BASE/source"
export BIN="$BASE/bin"
export MACOSX_DEPLOYMENT_TARGET=15.0
export _PYTHON_HOST_PLATFORM="macosx-15.0-arm64"
export ARCHFLAGS="-arch arm64"
export PKG_CONFIG_PATH="$BUILD/lib/pkgconfig"
export SDL2_DIR="$BUILD"
export PATH="/usr/local/bin:$PATH"
export SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

mkdir -p $SOURCE
mkdir -p $BIN

"$SCRIPT_DIR/build_libs"

cd "$PROJECT_DIR/scripts/mac/python"
versions=("3.10.11" "3.11.9" "3.12.9" "3.13.2" "3.14.2")
for version in "${versions[@]}"; do
    ./install_python $version
done

cd "$PROJECT_DIR"
#venvs=("py310" "py311" "py312" "py313" "py314")
venvs=("py313")
for venv in "${venvs[@]}"; do
    source $HOME/$venv/bin/activate
    python --version
    pip install build delocate
    python -m build .
    wheel=$(ls -1 dist/*${venv:2}*)
    echo $wheel
    delocate-wheel -w fixed_wheels --require-archs=arm64  -v $wheel
    deactivate
done
